#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Missing version"
  exit 1
fi

git tag -a -m "Version: $1" "$1"
git push --follow-tags

# sbt '+ mimaReportBinaryIssues ; tastyMiMaReportIssues ; + publishSigned ; sonatypeBundleRelease'
sbt '+ mimaReportBinaryIssues ; + publishSigned ; sonatypeBundleRelease'

