#!/usr/bin/env bash
# Display source code statistics
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
cd ${SCRIPT_DIR}/..

echo -e "\n### Files"
echo "* Main: `find  . -name '*.scala' -type f | grep src/main/ | wc -l`"
echo "* Test: `find  . -name '*.scala' -type f | grep src/test/ | wc -l`"
echo "* Docs: `(find  docs -name '*.md' -type f ; echo site/src/components/Home.js) | wc -l`"
echo "* Build: `(find . \( -name '*.sbt' \) -type f ; find site/src/components -type f ; cat <<EOF
site/package.json
site/docusaurus.config.js
EOF
) | wc -l`"

echo -e "\n### Lines"
echo "* Main: `find  . -name '*.scala' -type f | grep src/main/ | xargs cat | wc -l`"
echo "* Test: `find  . -name '*.scala' -type f | grep src/test/ | xargs cat | wc -l`"
echo "* Docs: `(find  docs -name '*.md' -type f ; echo site/src/components/Home.js) | xargs cat | wc -l`"
echo "* Build: `(find . \( -name '*.sbt' \) -type f ; find site/src/components -type f ; cat <<EOF
site/package.json
site/docusaurus.config.js
EOF
) | xargs cat | wc -l`"
echo

